[package]
name = "mock-relay"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.14.0", features = ["macros", "rt", "rt-multi-thread", "signal" ] }
clap = {version = "3.0.14", features = ["derive"]}
serde = "1.0.136"
serde_derive = "1.0.136"
tracing = "0.1"
tracing-subscriber = {version = "0.3.8", features = ["env-filter"]}
tracing-error = "0.2.0"
tracing-core = "0.1.21"
color-eyre = {version = "0.6.0", features = ["color-spantrace"]}
serde_json = "1.0.79"
execution_layer = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
types = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
task_executor = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
sensitive_url = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2 = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2_ssz_derive = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
exit-future = "0.2.0"
parking_lot = "0.12.0"
hex = "0.4.3"
slog = "2.7.0"
sloggers = "2.1.1"
futures-channel = "0.3.21"
tracing-slog = "0.1.0"
mev-rs = { git = "https://github.com/ralexstokes/mev-rs", rev = "7813d4a4a564e0754e9aaab2d95520ba437c3889" }
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "9b0ee0a8a45b968c8df5e7e64ea1c094e16f053d" }
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "adf1a0b14cef90b9536f28ef89da1fab316465e1" }
async-trait = "0.1.51"
rand = "0.8.5"
futures = "0.3.24"

[patch.crates-io]
eth2_serde_utils = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2_ssz_types = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
tree_hash = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2_ssz = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2_ssz_derive = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2 = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
eth2_hashing = { git = "https://github.com/ethDreamer/lighthouse", rev = "f6f5b2bce89ceca79fe2c75e49c8271c8e40598e" }
